Dark Sky API: 4ff1d8e73db78778122dfacfabf261f2

In [2]:
from darksky import forecast
from datetime import datetime as dt
from datetime import date, timedelta
import pandas as pd

Using Time Machine Call, we can get the observed weather conditions for a date in the past or future.

In [3]:
key = "4ff1d8e73db78778122dfacfabf261f2"
Fremont = key, 37.542, -121.991

In [4]:
t = dt(2018, 1, 1, 12).isoformat()
fre = forecast(*Fremont, t)
mydata = pd.DataFrame(fre['hourly']['data'])
mydata['LAT'] = 37.542
mydata['LON'] = -121.991
mydata['YEAR'] = 2018
mydata['MONTH'] = 1
mydata['DAY'] = 1
mydata['HOUR'] = [i for i in range(24)]

In [5]:
for i in range(2, 14):  
    t = dt(2018, 1, i, 12).isoformat()
    fre = forecast(*Fremont, t)
    tempdata = pd.DataFrame(fre['hourly']['data'])
    tempdata['LAT'] = 37.542
    tempdata['LON'] = -121.991
    tempdata['YEAR'] = 2018
    tempdata['MONTH'] = 1
    tempdata['DAY'] = i
    tempdata['HOUR'] = [i for i in range(24)]
    mydata = mydata.append(tempdata)
    
Jan_week = mydata

Save it as csv

In [6]:
Jan_week.to_csv("Jan_week.csv", sep=',')

In [7]:
Jan_week.head()

,DAY,HOUR,LAT,LON,MONTH,YEAR,apparentTemperature,cloudCover,dewPoint,humidity,...,precipIntensity,precipProbability,precipType,pressure,summary,temperature,time,visibility,windBearing,windSpeed
0,1,0,37.542,-121.991,1,2018,50.19,0.00,45.83,0.85,...,0.0,0.0,NaN,1022.88,Clear,50.19,1514793600,6.58,85,1.74
1,1,1,37.542,-121.991,1,2018,50.01,0.24,45.78,0.85,...,0.0,0.0,NaN,1022.79,Clear,50.01,1514797200,6.60,96,2.15
2,1,2,37.542,-121.991,1,2018,48.87,0.14,45.31,0.87,...,0.0,0.0,NaN,1022.79,Clear,48.87,1514800800,6.05,111,2.31
3,1,3,37.542,-121.991,1,2018,47.56,0.05,44.80,0.90,...,0.0,0.0,NaN,1022.89,Clear,47.56,1514804400,6.00,246,1.25
4,1,4,37.542,-121.991,1,2018,46.36,0.16,44.25,0.92,...,0.0,0.0,NaN,1023.05,Clear,46.36,1514808000,4.55,134,0.82

In [8]:
t = dt(2018, 2, 21, 12).isoformat()
fre = forecast(*Fremont, t)
mydata = pd.DataFrame(fre['hourly']['data'])
mydata['LAT'] = 37.542
mydata['LON'] = -121.991
mydata['YEAR'] = 2018
mydata['MONTH'] = 2
mydata['DAY'] = 21
mydata['HOUR'] = [i for i in range(24)]
for i in range(22, 29):  
    t = dt(2018, 2, i, 12).isoformat()
    fre = forecast(*Fremont, t)
    tempdata = pd.DataFrame(fre['hourly']['data'])
    tempdata['LAT'] = 37.542
    tempdata['LON'] = -121.991
    tempdata['YEAR'] = 2018
    tempdata['MONTH'] = 2
    tempdata['DAY'] = i
    tempdata['HOUR'] = [i for i in range(24)]
    Feb_week1 = mydata.append(tempdata)

In [13]:
t = dt(2018, 3, 1, 12).isoformat()
fre = forecast(*Fremont, t)
mydata = pd.DataFrame(fre['hourly']['data'])
mydata['LAT'] = 37.542
mydata['LON'] = -121.991
mydata['YEAR'] = 2018
mydata['MONTH'] = 3
mydata['DAY'] = 1
mydata['HOUR'] = [i for i in range(24)]
    
for i in range(2, 9):  
    t = dt(2018, 3, i, 12).isoformat()
    fre = forecast(*Fremont, t)
    tempdata = pd.DataFrame(fre['hourly']['data'])
    tempdata['LAT'] = 37.542
    tempdata['LON'] = -121.991
    tempdata['YEAR'] = 2018
    tempdata['MONTH'] = 3
    tempdata['DAY'] = i
    tempdata['HOUR'] = [i for i in range(24)]
    Feb_week2 = mydata.append(tempdata)
    
Feb_week = pd.concat([Feb_week1, Feb_week2])
Feb_week.to_csv("Feb_week.csv", sep=',')
Feb_week

,DAY,HOUR,LAT,LON,MONTH,YEAR,apparentTemperature,cloudCover,dewPoint,humidity,...,precipIntensity,precipProbability,precipType,pressure,summary,temperature,time,visibility,windBearing,windSpeed
0,21,0,37.542,-121.991,2,2018,44.11,0.18,33.55,0.66,...,0.0000,0.00,NaN,1022.60,Clear,44.11,1519200000,10.00,181,1.84
1,21,1,37.542,-121.991,2,2018,42.74,0.31,33.62,0.70,...,0.0000,0.00,NaN,1022.33,Partly Cloudy,42.74,1519203600,10.00,175,0.92
2,21,2,37.542,-121.991,2,2018,41.61,0.20,33.08,0.71,...,0.0000,0.00,NaN,1022.26,Clear,41.61,1519207200,10.00,121,2.77
3,21,3,37.542,-121.991,2,2018,36.77,0.05,32.84,0.75,...,0.0000,0.00,NaN,1021.51,Clear,40.13,1519210800,10.00,122,4.82
4,21,4,37.542,-121.991,2,2018,36.56,0.43,32.80,0.75,...,0.0000,0.00,NaN,1021.94,Partly Cloudy,39.93,1519214400,10.00,101,4.79
5,21,5,37.542,-121.991,2,2018,38.27,NaN,33.17,0.73,...,0.0000,0.00,NaN,1022.26,Clear,41.21,1519218000,10.00,129,4.52
6,21,6,37.542,-121.991,2,2018,38.85,NaN,33.26,0.72,...,0.0000,0.00,NaN,1022.40,Clear,41.47,1519221600,10.00,119,4.19
7,21,7,37.542,-121.991,2,2018,38.26,0.17,33.35,0.74,...,0.0000,0.00,NaN,1022.57,Clear,41.04,1519225200,10.00,105,4.30
8,21,8,37.542,-121.991,2,2018,39.66,0.21,34.65,0.74,...,0.0000,0.00,NaN,1022.94,Clear,42.33,1519228800,10.00,82,4.40
9,21,9,37.542,-121.991,2,2018,42.29,0.22,32.67,0.61,...,0.0000,0.00,NaN,1023.03,Clear,45.28,1519232400,10.00,83,5.59
10,21,10,37.542,-121.991,2,2018,48.45,0.23,33.23,0.55,...,0.0000,0.00,NaN,1023.16,Clear,48.45,1519236000,10.00,57,2.97
11,21,11,37.542,-121.991,2,2018,50.36,0.19,32.36,0.50,...,0.0000,0.00,NaN,1023.44,Clear,50.36,1519239600,10.00,4,2.66
12,21,12,37.542,-121.991,2,2018,51.49,0.22,30.94,0.45,...,0.0000,0.00,NaN,1023.17,Clear,51.49,1519243200,10.00,326,3.77
13,21,13,37.542,-121.991,2,2018,52.88,0.19,30.08,0.41,...,0.0000,0.00,NaN,1022.41,Clear,52.88,1519246800,10.00,319,4.74
14,21,14,37.542,-121.991,2,2018,54.46,0.19,25.84,0.33,...,0.0000,0.00,NaN,1022.12,Clear,54.46,1519250400,10.00,318,6.49
15,21,15,37.542,-121.991,2,2018,54.99,0.25,26.73,0.33,...,0.0000,0.00,NaN,1022.27,Partly Cloudy,54.99,1519254000,10.00,316,8.35
16,21,16,37.542,-121.991,2,2018,54.87,0.20,26.75,0.34,...,0.0000,0.00,NaN,1021.69,Clear,54.87,1519257600,10.00,312,6.23
17,21,17,37.542,-121.991,2,2018,53.92,0.22,27.72,0.36,...,0.0000,0.00,NaN,1021.53,Clear,53.92,1519261200,10.00,308,8.54
18,21,18,37.542,-121.991,2,2018,51.44,0.22,29.36,0.42,...,0.0000,0.00,NaN,1021.66,Clear,51.44,1519264800,10.00,296,8.89
19,21,19,37.542,-121.991,2,2018,45.11,0.07,32.80,0.53,...,0.0000,0.00,NaN,1022.11,Clear,49.41,1519268400,10.00,294,10.58
20,21,20,37.542,-121.991,2,2018,44.57,0.07,34.99,0.60,...,0.0000,0.00,NaN,1022.51,Clear,48.02,1519272000,10.00,299,7.51
21,21,21,37.542,-121.991,2,2018,44.13,0.05,35.94,0.66,...,0.0000,0.00,NaN,1022.79,Clear,46.80,1519275600,10.00,295,5.54
22,21,22,37.542,-121.991,2,2018,44.34,0.12,35.81,0.67,...,0.0000,0.00,NaN,1022.90,Clear,46.26,1519279200,10.00,266,4.27
23,21,23,37.542,-121.991,2,2018,42.20,0.13,35.94,0.71,...,0.0000,0.00,NaN,1023.40,Clear,44.77,1519282800,10.00,274,4.82
0,28,0,37.542,-121.991,2,2018,40.15,0.08,30.06,0.62,...,0.0000,0.00,NaN,1020.72,Clear,42.25,1519804800,10.00,123,3.74
1,28,1,37.542,-121.991,2,2018,41.71,0.08,30.82,0.65,...,0.0000,0.00,NaN,1021.15,Clear,41.71,1519808400,10.00,117,2.98
2,28,2,37.542,-121.991,2,2018,38.09,0.08,30.10,0.67,...,0.0000,0.00,NaN,1020.83,Clear,40.25,1519812000,10.00,123,3.51
3,28,3,37.542,-121.991,2,2018,37.06,0.08,30.37,0.69,...,0.0000,0.00,NaN,1020.65,Clear,39.86,1519815600,10.00,112,4.10
4,28,4,37.542,-121.991,2,2018,37.23,0.13,30.34,0.69,...,0.0000,0.00,NaN,1020.72,Clear,39.81,1519819200,10.00,121,3.86
5,28,5,37.542,-121.991,2,2018,36.02,0.05,30.40,0.69,...,0.0000,0.00,NaN,1021.17,Clear,39.67,1519822800,10.00,113,5.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,1,18,37.542,-121.991,3,2018,54.12,0.31,41.64,0.63,...,0.0000,0.00,NaN,1010.14,Partly Cloudy,54.12,1519956000,9.17,210,11.28
19,1,19,37.542,-121.991,3,2018,53.08,0.20,40.58,0.62,...,0.0000,0.00,NaN,1009.59,Clear,53.08,1519959600,9.17,191,12.13
20,1,20,37.542,-121.991,3,2018,53.21,0.20,41.47,0.64,...,0.0000,0.00,NaN,1009.71,Clear,53.21,1519963200,9.17,197,12.83
21,1,21,37.542,-121.991,3,2018,52.48,NaN,42.51,0.69,...,0.0078,0.20,rain,1009.80,Clear,52.48,1519966800,9.09,210,14.46
22,1,22,37.542,-121.991,3,2018,44.54,1.00,43.17,0.78,...,0.0431,0.81,rain,1010.74,Light Rain,49.90,1519970400,5.84,249,14.91
23,1,23,37.542,-121.991,3,2018,43.51,NaN,44.01,0.86,...,0.0497,1.00,rain,1011.47,Light Rain,48.12,1519974000,7.41,264,10.56
0,8,0,37.542,-121.991,3,2018,58.07,NaN,43.17,0.58,...,0.0020,0.20,rain,1018.44,Clear,58.07,1520496000,9.83,190,8.26
1,8,1,37.542,-121.991,3,2018,56.92,NaN,44.32,0.63,...,0.0000,0.00,NaN,1018.53,Clear,56.92,1520499600,10.00,184,4.75
2,8,2,37.542,-121.991,3,2018,56.07,NaN,46.13,0.69,...,0.0039,0.39,rain,1018.85,Clear,56.07,1520503200,7.81,145,3.14
3,8,3,37.542,-121.991,3,2018,54.38,NaN,49.57,0.84,...,0.0138,0.33,rain,1018.81,Clear,54.38,1520506800,8.29,125,4.15
4,8,4,37.542,-121.991,3,2018,53.86,1.00,49.26,0.84,...,0.0038,0.24,rain,1019.03,Overcast,53.86,1520510400,10.00,112,4.15
5,8,5,37.542,-121.991,3,2018,53.77,NaN,48.21,0.81,...,0.0000,0.00,NaN,1019.03,Clear,53.77,1520514000,10.00,134,3.91
6,8,6,37.542,-121.991,3,2018,54.06,NaN,48.78,0.82,...,0.0000,0.00,NaN,1019.33,Clear,54.06,1520517600,10.00,130,4.45
7,8,7,37.542,-121.991,3,2018,54.21,NaN,48.69,0.82,...,0.0000,0.00,NaN,1019.76,Clear,54.21,1520521200,10.00,113,3.43
8,8,8,37.542,-121.991,3,2018,55.69,NaN,48.33,0.76,...,0.0000,0.00,NaN,1020.29,Clear,55.69,1520524800,10.00,116,4.22
9,8,9,37.542,-121.991,3,2018,57.84,0.31,47.28,0.68,...,0.0000,0.00,NaN,1020.31,Partly Cloudy,57.84,1520528400,10.00,157,2.91
10,8,10,37.542,-121.991,3,2018,60.32,0.28,49.58,0.68,...,0.0000,0.00,NaN,1020.35,Partly Cloudy,60.32,1520532000,10.00,295,1.57
11,8,11,37.542,-121.991,3,2018,62.23,0.24,50.38,0.65,...,0.0000,0.00,NaN,1020.22,Clear,62.23,1520535600,10.00,350,6.21
12,8,12,37.542,-121.991,3,2018,63.78,0.31,52.14,0.66,...,0.0000,0.00,NaN,1020.03,Partly Cloudy,63.78,1520539200,10.00,314,6.74
13,8,13,37.542,-121.991,3,2018,64.75,0.31,52.13,0.64,...,0.0000,0.00,NaN,1019.72,Partly Cloudy,64.75,1520542800,10.00,319,9.89
14,8,14,37.542,-121.991,3,2018,64.59,0.31,52.77,0.66,...,0.0000,0.00,NaN,1018.96,Partly Cloudy,64.59,1520546400,10.00,311,11.86
15,8,15,37.542,-121.991,3,2018,64.51,0.31,52.38,0.65,...,0.0000,0.00,NaN,1018.45,Partly Cloudy,64.51,1520550000,10.00,308,11.63
16,8,16,37.542,-121.991,3,2018,63.25,0.37,51.83,0.66,...,0.0000,0.00,NaN,1018.03,Partly Cloudy,63.25,1520553600,10.00,312,10.27
17,8,17,37.542,-121.991,3,2018,61.75,0.20,51.29,0.69,...,0.0000,0.00,NaN,1017.49,Clear,61.75,1520557200,10.00,311,8.80
18,8,18,37.542,-121.991,3,2018,59.91,0.17,50.46,0.71,...,0.0000,0.00,NaN,1017.50,Clear,59.91,1520560800,10.00,300,6.88
19,8,19,37.542,-121.991,3,2018,57.34,0.31,50.63,0.78,...,0.0000,0.00,NaN,1017.91,Partly Cloudy,57.34,1520564400,10.00,299,5.98
20,8,20,37.542,-121.991,3,2018,56.20,0.31,50.87,0.82,...,0.0000,0.00,NaN,1018.07,Partly Cloudy,56.20,1520568000,10.00,313,5.64
21,8,21,37.542,-121.991,3,2018,55.45,0.22,50.37,0.83,...,0.0000,0.00,NaN,1018.33,Clear,55.45,1520571600,10.00,303,4.31
22,8,22,37.542,-121.991,3,2018,54.42,0.12,48.91,0.82,...,0.0000,0.00,NaN,1018.22,Clear,54.42,1520575200,10.00,300,3.73
23,8,23,37.542,-121.991,3,2018,53.12,0.13,48.97,0.86,...,0.0000,0.00,NaN,1017.87,Clear,53.12,1520578800,10.00,317,3.85

In [10]:

t = dt(2018, 3, 12, 12).isoformat()
fre = forecast(*Fremont, t)
mydata = pd.DataFrame(fre['hourly']['data'])
mydata['LAT'] = 37.542
mydata['LON'] = -121.991
mydata['YEAR'] = 2018
mydata['MONTH'] = 3
mydata['DAY'] = 12
mydata['HOUR'] = [i for i in range(24)]
    
for i in range(13, 27):  
    t = dt(2018, 3, i, 12).isoformat()
    fre = forecast(*Fremont, t)
    tempdata = pd.DataFrame(fre['hourly']['data'])
    tempdata['LAT'] = 37.542
    tempdata['LON'] = -121.991
    tempdata['YEAR'] = 2018
    tempdata['MONTH'] = 3
    tempdata['DAY'] = i
    tempdata['HOUR'] = [i for i in range(24)]
    Mar_week = mydata.append(tempdata)
    
Mar_week.to_csv("Mar_week.csv", sep=',')
Mar_week.head()

,DAY,HOUR,LAT,LON,MONTH,YEAR,apparentTemperature,cloudCover,dewPoint,humidity,...,precipIntensity,precipProbability,precipType,pressure,summary,temperature,time,visibility,windBearing,windSpeed
0,12,0,37.542,-121.991,3,2018,55.31,0.23,48.53,0.78,...,0.0,0.0,NaN,1019.30,Clear,55.31,1520838000,10.00,325,2.08
1,12,1,37.542,-121.991,3,2018,54.34,0.13,48.49,0.81,...,0.0,0.0,NaN,1019.07,Clear,54.34,1520841600,9.90,296,1.60
2,12,2,37.542,-121.991,3,2018,53.84,0.16,48.72,0.83,...,0.0,0.0,NaN,1019.27,Clear,53.84,1520845200,10.00,303,1.69
3,12,3,37.542,-121.991,3,2018,53.10,0.00,48.80,0.85,...,0.0,0.0,NaN,1019.09,Clear,53.10,1520848800,10.00,321,1.54
4,12,4,37.542,-121.991,3,2018,52.28,0.15,48.85,0.88,...,0.0,0.0,NaN,1018.20,Clear,52.28,1520852400,9.88,103,1.13

In [11]:
t = dt(2018, 4, 2, 12).isoformat()
fre = forecast(*Fremont, t)
mydata = pd.DataFrame(fre['hourly']['data'])
mydata['LAT'] = 37.542
mydata['LON'] = -121.991
mydata['YEAR'] = 2018
mydata['MONTH'] = 4
mydata['DAY'] = 2
mydata['HOUR'] = [i for i in range(24)]
    
for i in range(3, 15):  
    t = dt(2018, 4, i, 12).isoformat()
    fre = forecast(*Fremont, t)
    tempdata = pd.DataFrame(fre['hourly']['data'])
    tempdata['LAT'] = 37.542
    tempdata['LON'] = -121.991
    tempdata['YEAR'] = 2018
    tempdata['MONTH'] = 4
    tempdata['DAY'] = i
    tempdata['HOUR'] = [i for i in range(24)]
    Apr_week = mydata.append(tempdata)
    
Apr_week.to_csv("Apr_week.csv", sep=',')
Apr_week.head()

,apparentTemperature,cloudCover,dewPoint,humidity,icon,precipIntensity,precipProbability,pressure,summary,temperature,time,visibility,windBearing,windSpeed,LAT,LON,YEAR,MONTH,DAY,HOUR
0,55.43,0.08,47.94,0.76,clear-night,0,0,1012.88,Clear,55.43,1522652400,10.00,227,3.11,37.542,-121.991,2018,4,2,0
1,54.45,0.08,48.12,0.79,clear-night,0,0,1013.04,Clear,54.45,1522656000,10.00,247,2.35,37.542,-121.991,2018,4,2,1
2,54.04,0.04,48.13,0.80,clear-night,0,0,1012.88,Clear,54.04,1522659600,9.78,245,2.52,37.542,-121.991,2018,4,2,2
3,53.33,0.04,48.27,0.83,clear-night,0,0,1012.66,Clear,53.33,1522663200,9.88,235,2.33,37.542,-121.991,2018,4,2,3
4,52.88,0.04,48.12,0.84,clear-night,0,0,1012.29,Clear,52.88,1522666800,9.78,202,3.42,37.542,-121.991,2018,4,2,4

In [19]:
Rain_week = pd.concat([Jan_week, Feb_week, Mar_week, Apr_week])
Rain_week.to_csv("Rain_week.csv", sep=',')
Rain_week.head()

,DAY,HOUR,LAT,LON,MONTH,YEAR,apparentTemperature,cloudCover,dewPoint,humidity,...,precipIntensity,precipProbability,precipType,pressure,summary,temperature,time,visibility,windBearing,windSpeed
0,1,0,37.542,-121.991,1,2018,50.19,0.00,45.83,0.85,...,0.0,0.0,NaN,1022.88,Clear,50.19,1514793600,6.58,85,1.74
1,1,1,37.542,-121.991,1,2018,50.01,0.24,45.78,0.85,...,0.0,0.0,NaN,1022.79,Clear,50.01,1514797200,6.60,96,2.15
2,1,2,37.542,-121.991,1,2018,48.87,0.14,45.31,0.87,...,0.0,0.0,NaN,1022.79,Clear,48.87,1514800800,6.05,111,2.31
3,1,3,37.542,-121.991,1,2018,47.56,0.05,44.80,0.90,...,0.0,0.0,NaN,1022.89,Clear,47.56,1514804400,6.00,246,1.25
4,1,4,37.542,-121.991,1,2018,46.36,0.16,44.25,0.92,...,0.0,0.0,NaN,1023.05,Clear,46.36,1514808000,4.55,134,0.82